name: My First Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show system info
        run: |
          uname -a
          python --version

      - name: List files
        run: ls -la